var searchData=
[
  ['randomprobabilitygenerator_0',['RandomProbabilityGenerator',['../d3/dae/classstorm_1_1utility_1_1_random_probability_generator.html',1,'storm::utility']]],
  ['randomprobabilitygenerator_3c_20double_20_3e_1',['RandomProbabilityGenerator&lt; double &gt;',['../d6/d94/classstorm_1_1utility_1_1_random_probability_generator_3_01double_01_4.html',1,'storm::utility']]],
  ['randomprobabilitygenerator_3c_20storm_3a_3arationalnumber_20_3e_2',['RandomProbabilityGenerator&lt; storm::RationalNumber &gt;',['../da/d29/classstorm_1_1utility_1_1_random_probability_generator_3_01storm_1_1_rational_number_01_4.html',1,'storm::utility']]],
  ['rangeargumentvalidator_3',['RangeArgumentValidator',['../d3/d44/classstorm_1_1settings_1_1_range_argument_validator.html',1,'storm::settings']]],
  ['rationalfunction_4',['RationalFunction',['../db/df5/classcarl_1_1_rational_function.html',1,'carl']]],
  ['rationalfunctionconstructor_5',['RationalFunctionConstructor',['../da/d4d/structstorm_1_1transformer_1_1_rational_function_constructor.html',1,'storm::transformer']]],
  ['rationalfunctiontoexpression_6',['RationalFunctionToExpression',['../dc/d0f/classstorm_1_1expressions_1_1_rational_function_to_expression.html',1,'storm::expressions']]],
  ['rationalliteralexpression_7',['RationalLiteralExpression',['../d5/d8f/classstorm_1_1expressions_1_1_rational_literal_expression.html',1,'storm::expressions']]],
  ['rationalpolicies_8',['RationalPolicies',['../d0/d9e/structstorm_1_1parser_1_1_rational_policies.html',1,'storm::parser']]],
  ['rationalsearchhelper_9',['RationalSearchHelper',['../d8/d0f/classstorm_1_1solver_1_1helper_1_1_rational_search_helper.html',1,'storm::solver::helper']]],
  ['rationaltype_10',['RationalType',['../d8/d1e/classstorm_1_1expressions_1_1_rational_type.html',1,'storm::expressions']]],
  ['rawlpconstraint_11',['RawLpConstraint',['../da/d17/structstorm_1_1solver_1_1_raw_lp_constraint.html',1,'storm::solver']]],
  ['rebuildwithoutunreachableaction_12',['RebuildWithoutUnreachableAction',['../de/dfd/classstorm_1_1jani_1_1elimination__actions_1_1_rebuild_without_unreachable_action.html',1,'storm::jani::elimination_actions']]],
  ['reducenestingvisitor_13',['ReduceNestingVisitor',['../d7/d8d/classstorm_1_1expressions_1_1_reduce_nesting_visitor.html',1,'storm::expressions']]],
  ['reducevertexcloud_14',['ReduceVertexCloud',['../d9/d27/classstorm_1_1storage_1_1geometry_1_1_reduce_vertex_cloud.html',1,'storm::storage::geometry']]],
  ['refinementcommand_15',['RefinementCommand',['../d8/da9/classstorm_1_1gbar_1_1abstraction_1_1_refinement_command.html',1,'storm::gbar::abstraction']]],
  ['refinementpredicates_16',['RefinementPredicates',['../d3/d1a/classstorm_1_1gbar_1_1abstraction_1_1_refinement_predicates.html',1,'storm::gbar::abstraction']]],
  ['refinementstep_17',['RefinementStep',['../d2/d24/structstorm_1_1modelchecker_1_1multiobjective_1_1_sparse_pcaa_query_1_1_refinement_step.html',1,'storm::modelchecker::multiobjective::SparsePcaaQuery']]],
  ['regionbound_18',['RegionBound',['../dd/df3/structstorm_1_1modelchecker_1_1_region_bound.html',1,'storm::modelchecker']]],
  ['regioncheckresult_19',['RegionCheckResult',['../d8/d53/classstorm_1_1modelchecker_1_1_region_check_result.html',1,'storm::modelchecker']]],
  ['regionmodelchecker_20',['RegionModelChecker',['../d0/d24/classstorm_1_1modelchecker_1_1_region_model_checker.html',1,'storm::modelchecker']]],
  ['regionmodelchecker_3c_20sparsemodeltype_3a_3avaluetype_20_3e_21',['RegionModelChecker&lt; SparseModelType::ValueType &gt;',['../d0/d24/classstorm_1_1modelchecker_1_1_region_model_checker.html',1,'storm::modelchecker']]],
  ['regionrefinementcheckresult_22',['RegionRefinementCheckResult',['../d7/d01/classstorm_1_1modelchecker_1_1_region_refinement_check_result.html',1,'storm::modelchecker']]],
  ['regionsettings_23',['RegionSettings',['../df/dae/classstorm_1_1settings_1_1modules_1_1_region_settings.html',1,'storm::settings::modules']]],
  ['regionverificationsettings_24',['RegionVerificationSettings',['../d0/d1b/classstorm_1_1settings_1_1modules_1_1_region_verification_settings.html',1,'storm::settings::modules']]],
  ['relevantevents_25',['RelevantEvents',['../d3/d28/classstorm_1_1dft_1_1utility_1_1_relevant_events.html',1,'storm::dft::utility']]],
  ['renamingcomposition_26',['RenamingComposition',['../d9/d43/classstorm_1_1prism_1_1_renaming_composition.html',1,'storm::prism']]],
  ['replacement_27',['Replacement',['../d6/d9a/classstorm_1_1jani_1_1_array_eliminator_data_1_1_replacement.html',1,'storm::jani::ArrayEliminatorData']]],
  ['resourcesettings_28',['ResourceSettings',['../d0/def/classstorm_1_1settings_1_1modules_1_1_resource_settings.html',1,'storm::settings::modules']]],
  ['restrictedparallelcomposition_29',['RestrictedParallelComposition',['../d3/d0e/classstorm_1_1prism_1_1_restricted_parallel_composition.html',1,'storm::prism']]],
  ['restrictsyntaxvisitor_30',['RestrictSyntaxVisitor',['../d2/d2c/classstorm_1_1expressions_1_1_restrict_syntax_visitor.html',1,'storm::expressions']]],
  ['result_31',['result',['../d3/d69/structstorm_1_1parser_1_1_markov_automaton_sparse_transition_parser_1_1_result.html',1,'storm::parser::MarkovAutomatonSparseTransitionParser&lt; ValueType &gt;::Result'],['../df/d31/structstorm_1_1pomdp_1_1modelchecker_1_1_belief_exploration_pomdp_model_checker_1_1_result.html',1,'storm::pomdp::modelchecker::BeliefExplorationPomdpModelChecker&lt; PomdpModelType, BeliefValueType, BeliefMDPType &gt;::Result']]],
  ['resultoutputvisitor_32',['ResultOutputVisitor',['../da/d01/classstorm_1_1dft_1_1modelchecker_1_1_d_f_t_model_checker_1_1_result_output_visitor.html',1,'storm::dft::modelchecker::DFTModelChecker']]],
  ['resulttype_33',['resulttype',['../d5/da7/structstorm_1_1jani_1_1_assignments_finder_1_1_result_type.html',1,'storm::jani::AssignmentsFinder::ResultType'],['../d1/db4/classstorm_1_1jani_1_1detail_1_1_array_expression_elimination_visitor_1_1_result_type.html',1,'storm::jani::detail::ArrayExpressionEliminationVisitor::ResultType']]],
  ['returntype_34',['returntype',['../d4/da4/structstorm_1_1transformer_1_1_goal_state_merger_1_1_return_type.html',1,'storm::transformer::GoalStateMerger&lt; SparseModelType &gt;::ReturnType'],['../d7/d50/structstorm_1_1modelchecker_1_1multiobjective_1_1preprocessing_1_1_sparse_multi_objective_reward_analysis_1_1_return_type.html',1,'storm::modelchecker::multiobjective::preprocessing::SparseMultiObjectiveRewardAnalysis&lt; SparseModelType &gt;::ReturnType'],['../d4/d07/structstorm_1_1jani_1_1_jani_location_expander_1_1_return_type.html',1,'storm::jani::JaniLocationExpander::ReturnType']]],
  ['reusewrapper_35',['ReuseWrapper',['../df/d1d/classstorm_1_1dd_1_1bisimulation_1_1_reuse_wrapper.html',1,'storm::dd::bisimulation']]],
  ['rewardaccumulation_36',['RewardAccumulation',['../d2/db9/classstorm_1_1logic_1_1_reward_accumulation.html',1,'storm::logic']]],
  ['rewardaccumulationeliminationvisitor_37',['RewardAccumulationEliminationVisitor',['../d8/dad/classstorm_1_1logic_1_1_reward_accumulation_elimination_visitor.html',1,'storm::logic']]],
  ['rewardboundedmdppcaaweightvectorchecker_38',['RewardBoundedMdpPcaaWeightVectorChecker',['../d0/d85/classstorm_1_1modelchecker_1_1multiobjective_1_1_reward_bounded_mdp_pcaa_weight_vector_checker.html',1,'storm::modelchecker::multiobjective']]],
  ['rewardmodel_39',['RewardModel',['../d8/d77/classstorm_1_1prism_1_1_reward_model.html',1,'storm::prism']]],
  ['rewardmodelbuilder_40',['RewardModelBuilder',['../d1/d78/classstorm_1_1builder_1_1_reward_model_builder.html',1,'storm::builder']]],
  ['rewardmodelinformation_41',['rewardmodelinformation',['../da/d73/classstorm_1_1builder_1_1_reward_model_information.html',1,'storm::builder::RewardModelInformation'],['../dc/ddc/classstorm_1_1jani_1_1_reward_model_information.html',1,'storm::jani::RewardModelInformation']]],
  ['rewardmodelnamesubstitutionvisitor_42',['RewardModelNameSubstitutionVisitor',['../d6/dbf/classstorm_1_1logic_1_1_reward_model_name_substitution_visitor.html',1,'storm::logic']]],
  ['rewardoperatorformula_43',['RewardOperatorFormula',['../d7/db3/classstorm_1_1logic_1_1_reward_operator_formula.html',1,'storm::logic']]],
  ['rows_44',['rows',['../d5/dd0/classstorm_1_1storage_1_1_sparse_matrix_1_1rows.html',1,'storm::storage::SparseMatrix']]],
  ['rsbackend_45',['RSBackend',['../d6/d3b/classstorm_1_1solver_1_1helper_1_1_r_s_backend.html',1,'storm::solver::helper']]]
];
