var searchData=
[
  ['randomprobabilitygenerator_9791',['RandomProbabilityGenerator',['../d3/dae/classstorm_1_1utility_1_1_random_probability_generator.html',1,'storm::utility']]],
  ['randomprobabilitygenerator_3c_20double_20_3e_9792',['RandomProbabilityGenerator&lt; double &gt;',['../d6/d94/classstorm_1_1utility_1_1_random_probability_generator_3_01double_01_4.html',1,'storm::utility']]],
  ['randomprobabilitygenerator_3c_20storm_3a_3arationalnumber_20_3e_9793',['RandomProbabilityGenerator&lt; storm::RationalNumber &gt;',['../da/d29/classstorm_1_1utility_1_1_random_probability_generator_3_01storm_1_1_rational_number_01_4.html',1,'storm::utility']]],
  ['rangeargumentvalidator_9794',['RangeArgumentValidator',['../d3/d44/classstorm_1_1settings_1_1_range_argument_validator.html',1,'storm::settings']]],
  ['rationalfunctionconstructor_9795',['RationalFunctionConstructor',['../da/d4d/structstorm_1_1transformer_1_1_rational_function_constructor.html',1,'storm::transformer']]],
  ['rationalfunctiontoexpression_9796',['RationalFunctionToExpression',['../dc/d0f/classstorm_1_1expressions_1_1_rational_function_to_expression.html',1,'storm::expressions']]],
  ['rationalliteralexpression_9797',['RationalLiteralExpression',['../d5/d8f/classstorm_1_1expressions_1_1_rational_literal_expression.html',1,'storm::expressions']]],
  ['rationalpolicies_9798',['RationalPolicies',['../d0/d9e/structstorm_1_1parser_1_1_rational_policies.html',1,'storm::parser']]],
  ['rationaltype_9799',['RationalType',['../d8/d1e/classstorm_1_1expressions_1_1_rational_type.html',1,'storm::expressions']]],
  ['realvariable_9800',['RealVariable',['../d8/dc7/classstorm_1_1jani_1_1_real_variable.html',1,'storm::jani']]],
  ['reducenestingvisitor_9801',['ReduceNestingVisitor',['../d7/d8d/classstorm_1_1expressions_1_1_reduce_nesting_visitor.html',1,'storm::expressions']]],
  ['reducevertexcloud_9802',['ReduceVertexCloud',['../d9/d27/classstorm_1_1storage_1_1geometry_1_1_reduce_vertex_cloud.html',1,'storm::storage::geometry']]],
  ['refinementcommand_9803',['RefinementCommand',['../d6/db1/classstorm_1_1abstraction_1_1_refinement_command.html',1,'storm::abstraction']]],
  ['refinementpredicates_9804',['RefinementPredicates',['../df/d6e/classstorm_1_1abstraction_1_1_refinement_predicates.html',1,'storm::abstraction']]],
  ['refinementstep_9805',['RefinementStep',['../d2/d24/structstorm_1_1modelchecker_1_1multiobjective_1_1_sparse_pcaa_query_1_1_refinement_step.html',1,'storm::modelchecker::multiobjective::SparsePcaaQuery']]],
  ['regionbound_9806',['RegionBound',['../dd/df3/structstorm_1_1modelchecker_1_1_region_bound.html',1,'storm::modelchecker']]],
  ['regioncheckresult_9807',['RegionCheckResult',['../d8/d53/classstorm_1_1modelchecker_1_1_region_check_result.html',1,'storm::modelchecker']]],
  ['regionmodelchecker_9808',['RegionModelChecker',['../d0/d24/classstorm_1_1modelchecker_1_1_region_model_checker.html',1,'storm::modelchecker']]],
  ['regionmodelchecker_3c_20sparsemodeltype_3a_3avaluetype_20_3e_9809',['RegionModelChecker&lt; SparseModelType::ValueType &gt;',['../d0/d24/classstorm_1_1modelchecker_1_1_region_model_checker.html',1,'storm::modelchecker']]],
  ['regionrefinementcheckresult_9810',['RegionRefinementCheckResult',['../d7/d01/classstorm_1_1modelchecker_1_1_region_refinement_check_result.html',1,'storm::modelchecker']]],
  ['regionsettings_9811',['RegionSettings',['../df/dae/classstorm_1_1settings_1_1modules_1_1_region_settings.html',1,'storm::settings::modules']]],
  ['relevantevents_9812',['RelevantEvents',['../d2/daa/classstorm_1_1utility_1_1_relevant_events.html',1,'storm::utility']]],
  ['renamingcomposition_9813',['RenamingComposition',['../d9/d43/classstorm_1_1prism_1_1_renaming_composition.html',1,'storm::prism']]],
  ['resourcesettings_9814',['ResourceSettings',['../d0/def/classstorm_1_1settings_1_1modules_1_1_resource_settings.html',1,'storm::settings::modules']]],
  ['restrictedparallelcomposition_9815',['RestrictedParallelComposition',['../d3/d0e/classstorm_1_1prism_1_1_restricted_parallel_composition.html',1,'storm::prism']]],
  ['restrictiongrouptohash_9816',['RestrictionGroupToHash',['../dd/d20/structstorm_1_1storage_1_1_restriction_group_to_hash.html',1,'storm::storage']]],
  ['result_9817',['Result',['../d3/d69/structstorm_1_1parser_1_1_markov_automaton_sparse_transition_parser_1_1_result.html',1,'storm::parser::MarkovAutomatonSparseTransitionParser&lt; ValueType &gt;::Result'],['../df/d31/structstorm_1_1pomdp_1_1modelchecker_1_1_belief_exploration_pomdp_model_checker_1_1_result.html',1,'storm::pomdp::modelchecker::BeliefExplorationPomdpModelChecker&lt; PomdpModelType, BeliefValueType &gt;::Result']]],
  ['resultoutputvisitor_9818',['ResultOutputVisitor',['../d6/db6/classstorm_1_1modelchecker_1_1_d_f_t_model_checker_1_1_result_output_visitor.html',1,'storm::modelchecker::DFTModelChecker']]],
  ['resulttype_9819',['ResultType',['../d5/da7/structstorm_1_1jani_1_1_assignments_finder_1_1_result_type.html',1,'storm::jani::AssignmentsFinder::ResultType'],['../d1/db4/classstorm_1_1jani_1_1detail_1_1_array_expression_elimination_visitor_1_1_result_type.html',1,'storm::jani::detail::ArrayExpressionEliminationVisitor::ResultType']]],
  ['returntype_9820',['ReturnType',['../d7/d50/structstorm_1_1modelchecker_1_1multiobjective_1_1preprocessing_1_1_sparse_multi_objective_reward_analysis_1_1_return_type.html',1,'storm::modelchecker::multiobjective::preprocessing::SparseMultiObjectiveRewardAnalysis&lt; SparseModelType &gt;::ReturnType'],['../d4/da4/structstorm_1_1transformer_1_1_goal_state_merger_1_1_return_type.html',1,'storm::transformer::GoalStateMerger&lt; SparseModelType &gt;::ReturnType']]],
  ['reusewrapper_9821',['ReuseWrapper',['../df/d1d/classstorm_1_1dd_1_1bisimulation_1_1_reuse_wrapper.html',1,'storm::dd::bisimulation']]],
  ['rewardaccumulation_9822',['RewardAccumulation',['../d2/db9/classstorm_1_1logic_1_1_reward_accumulation.html',1,'storm::logic']]],
  ['rewardaccumulationeliminationvisitor_9823',['RewardAccumulationEliminationVisitor',['../d8/dad/classstorm_1_1logic_1_1_reward_accumulation_elimination_visitor.html',1,'storm::logic']]],
  ['rewardboundedmdppcaaweightvectorchecker_9824',['RewardBoundedMdpPcaaWeightVectorChecker',['../d0/d85/classstorm_1_1modelchecker_1_1multiobjective_1_1_reward_bounded_mdp_pcaa_weight_vector_checker.html',1,'storm::modelchecker::multiobjective']]],
  ['rewardmodel_9825',['RewardModel',['../d8/d77/classstorm_1_1prism_1_1_reward_model.html',1,'storm::prism']]],
  ['rewardmodelbuilder_9826',['RewardModelBuilder',['../d1/d78/classstorm_1_1builder_1_1_reward_model_builder.html',1,'storm::builder']]],
  ['rewardmodelinformation_9827',['RewardModelInformation',['../dc/ddc/classstorm_1_1jani_1_1_reward_model_information.html',1,'storm::jani::RewardModelInformation'],['../da/d73/classstorm_1_1builder_1_1_reward_model_information.html',1,'storm::builder::RewardModelInformation']]],
  ['rewardmodelnamesubstitutionvisitor_9828',['RewardModelNameSubstitutionVisitor',['../d6/dbf/classstorm_1_1logic_1_1_reward_model_name_substitution_visitor.html',1,'storm::logic']]],
  ['rewardoperatorformula_9829',['RewardOperatorFormula',['../d7/db3/classstorm_1_1logic_1_1_reward_operator_formula.html',1,'storm::logic']]],
  ['rows_9830',['rows',['../d5/dd0/classstorm_1_1storage_1_1_sparse_matrix_1_1rows.html',1,'storm::storage::SparseMatrix']]]
];
